<a href="https://colab.research.google.com/github/meghana507/ai-ml-practice-project/blob/main/Building_auto_tagging_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Objective

Build a model to automatically predict tags for a given a StackExchange question by using the text of the question.
![alt text](https://cdn.sstatic.net/Sites/stackoverflow/company/img/logos/se/se-logo.svg?v=d29f0785ebb7)

__Dataset Specs__: Over 85,000 questions

[Download Link](https://www.kaggle.com/stackoverflow/statsquestions#Questions.csv)

__License__

All Stack Exchange user contributions are licensed under [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) with [attribution required](http://blog.stackoverflow.com/2009/06/attribution-required/).

<br>

***

In [53]:
# mount Google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Steps to Follow



1. Load Data and Import Libraries
2. Text Cleaning
3. Merge Tags with Questions
4. Dataset Preparation
5. Text Representation
6. Model Building
    1. Define Model Architecture
    2. Train the Model
7. Model Predictions
8. Model Evaluation

# Load Data and Import Libraries

In [54]:
# for string matching
import re

# for reading data
import pandas as pd

# for handling html data
from bs4 import BeautifulSoup

# for visualization
import matplotlib.pyplot as plt

pd.set_option('display.max_colwidth', 200)

In [55]:
# extract data from the ZIP file
!unzip '/content/drive/MyDrive/archive (2).zip'

Archive:  /content/drive/MyDrive/archive (2).zip
replace Answers.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [56]:
# load the stackoverflow questions dataset
questions_df = pd.read_csv('Questions.csv',encoding='latin-1')

# load the tags dataset
tags_df = pd.read_csv('Tags.csv')

In [57]:
questions_df.shape, tags_df.shape

((85085, 6), (244228, 2))

In [58]:
tags_df.head()

   Id            Tag
0   1       bayesian
1   1          prior
2   1    elicitation
3   2  distributions
4   2      normality

### Data Dictionary

1. Id: Question ID
2. OwnerUserId: User ID
3. CreationDate: Date of posting question
4. Score: Count of Upvotes received by the question
5. Title: Title of the question
6. Body: Text body of the question

In [59]:
#print first 5 rows
questions_df.head()

,Id,OwnerUserId,CreationDate,Score,Title,Body
0,6,5.0,2010-07-19T19:14:44Z,272,The Two Cultures: statistics vs. machine learning?,"<p>Last year, I read a blog post from <a href=""http://anyall.org/"">Brendan O'Connor</a> entitled <a href=""http://anyall.org/blog/2008/12/statistics-vs-machine-learning-fight/"">""Statistics vs. Mach..."
1,21,59.0,2010-07-19T19:24:36Z,4,Forecasting demographic census,<p>What are some of the ways to forecast demographic census with some validation and calibration techniques?</p>\n\n<p>Some of the concerns:</p>\n\n<ul>\n<li>Census blocks vary in sizes as rural\n...
2,22,66.0,2010-07-19T19:25:39Z,208,Bayesian and frequentist reasoning in plain English,<p>How would you describe in plain English the characteristics that distinguish Bayesian from Frequentist reasoning?</p>\n
3,31,13.0,2010-07-19T19:28:44Z,138,What is the meaning of p values and t values in statistical tests?,"<p>After taking a statistics course and then trying to help fellow students, I noticed one subject that inspires much head-desk banging is interpreting the results of statistical hypothesis tests...."
4,36,8.0,2010-07-19T19:31:47Z,58,Examples for teaching: Correlation does not mean causation,"<p>There is an old saying: ""Correlation does not mean causation"". When I teach, I tend to use the following standard examples to illustrate this point:</p>\n\n<ol>\n<li>number of storks and birth ..."

# Text Cleaning

Let's define a function to clean the text data.

In [60]:
def cleaner(text):

  # take off html tags
  text = BeautifulSoup(text).get_text()

  # fetch alphabetic characters
  text = re.sub("[^a-zA-Z]", " ", text)

  # convert text to lower case
  text = text.lower()

  # split text into tokens to remove whitespaces
  tokens = text.split()

  return " ".join(tokens)

In [61]:
# call preprocessing function
questions_df['cleaned_text'] = questions_df['Body'].apply(cleaner)

In [62]:
questions_df['Body'][1]

"<p>What are some of the ways to forecast demographic census with some validation and calibration techniques?</p>\n\n<p>Some of the concerns:</p>\n\n<ul>\n<li>Census blocks vary in sizes as rural\nareas are a lot larger than condensed\nurban areas. Is there a need to account for the area size difference?</li>\n<li>if let's say I have census data\ndating back to 4 - 5 census periods,\nhow far can i forecast it into the\nfuture?</li>\n<li>if some of the census zone change\nlightly in boundaries, how can i\naccount for that change?</li>\n<li>What are the methods to validate\ncensus forecasts? for example, if i\nhave data for existing 5 census\nperiods, should I model the first 3\nand test it on the latter two? or is\nthere another way?</li>\n<li>what's the state of practice in\nforecasting census data, and what are\nsome of the state of the art methods?</li>\n</ul>\n"

In [63]:
questions_df['cleaned_text'][1]

'what are some of the ways to forecast demographic census with some validation and calibration techniques some of the concerns census blocks vary in sizes as rural areas are a lot larger than condensed urban areas is there a need to account for the area size difference if let s say i have census data dating back to census periods how far can i forecast it into the future if some of the census zone change lightly in boundaries how can i account for that change what are the methods to validate census forecasts for example if i have data for existing census periods should i model the first and test it on the latter two or is there another way what s the state of practice in forecasting census data and what are some of the state of the art methods'

# Merge Tags with Questions

Let's now explore the tags data.

In [64]:
tags_df.head()

   Id            Tag
0   1       bayesian
1   1          prior
2   1    elicitation
3   2  distributions
4   2      normality

In [65]:
# count of unique tags
len(tags_df['Tag'].unique())

1315

In [66]:
tags_df['Tag'].value_counts()

Tag
r                            13236
regression                   10959
machine-learning              6089
time-series                   5559
probability                   4217
                             ...
dimensions                       1
fmincon                          1
american-community-survey        1
propensity                       1
corpus-linguistics               1
Name: count, Length: 1315, dtype: int64

In [67]:
# remove "-" from the tags
tags_df['Tag']= tags_df['Tag'].apply(lambda x:re.sub("-"," ",x))

In [68]:
# group tags Id wise
tags_df = tags_df.groupby('Id').apply(lambda x:x['Tag'].values).reset_index(name='tags')
tags_df.head()

/tmp/ipykernel_7252/2461770040.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tags_df = tags_df.groupby('Id').apply(lambda x:x['Tag'].values).reset_index(name='tags')

   Id                                       tags
0   1             [bayesian, prior, elicitation]
1   2                 [distributions, normality]
2   3                    [software, open source]
3   4  [distributions, statistical significance]
4   6                         [machine learning]

In [69]:
# merge tags and questions
df = pd.merge(questions_df,tags_df,how='inner',on='Id')

In [70]:
df = df[['Id','Body','cleaned_text','tags']]
df.head()

,Id,Body,cleaned_text,tags
0,6,"<p>Last year, I read a blog post from <a href=""http://anyall.org/"">Brendan O'Connor</a> entitled <a href=""http://anyall.org/blog/2008/12/statistics-vs-machine-learning-fight/"">""Statistics vs. Mach...",last year i read a blog post from brendan o connor entitled statistics vs machine learning fight that discussed some of the differences between the two fields andrew gelman responded favorably to ...,[machine learning]
1,21,<p>What are some of the ways to forecast demographic census with some validation and calibration techniques?</p>\n\n<p>Some of the concerns:</p>\n\n<ul>\n<li>Census blocks vary in sizes as rural\n...,what are some of the ways to forecast demographic census with some validation and calibration techniques some of the concerns census blocks vary in sizes as rural areas are a lot larger than conde...,"[forecasting, population, census]"
2,22,<p>How would you describe in plain English the characteristics that distinguish Bayesian from Frequentist reasoning?</p>\n,how would you describe in plain english the characteristics that distinguish bayesian from frequentist reasoning,"[bayesian, frequentist]"
3,31,"<p>After taking a statistics course and then trying to help fellow students, I noticed one subject that inspires much head-desk banging is interpreting the results of statistical hypothesis tests....",after taking a statistics course and then trying to help fellow students i noticed one subject that inspires much head desk banging is interpreting the results of statistical hypothesis tests it s...,"[hypothesis testing, t test, p value, interpretation, intuition]"
4,36,"<p>There is an old saying: ""Correlation does not mean causation"". When I teach, I tend to use the following standard examples to illustrate this point:</p>\n\n<ol>\n<li>number of storks and birth ...",there is an old saying correlation does not mean causation when i teach i tend to use the following standard examples to illustrate this point number of storks and birth rate in denmark number of ...,"[correlation, teaching]"

In [71]:
df.shape

(85085, 4)

There are over 85,000 unique questions and over 1300 tags.

# Dataset Preparation

In [72]:
# check frequency of occurence of each tag
freq= {}
for i in df['tags']:
  for j in i:
    if j in freq.keys():
      freq[j] = freq[j] + 1
    else:
      freq[j] = 1

Let's find out the most frequent tags.

In [73]:
# sort the dictionary in descending order
freq = dict(sorted(freq.items(), key=lambda x:x[1],reverse=True))

In [74]:
freq.items()

dict_items([('r', 13236), ('regression', 10959), ('machine learning', 6089), ('time series', 5559), ('probability', 4217), ('hypothesis testing', 3869), ('self study', 3732), ('distributions', 3501), ('logistic', 3316), ('classification', 2881), ('correlation', 2871), ('statistical significance', 2666), ('bayesian', 2656), ('anova', 2505), ('normal distribution', 2181), ('multiple regression', 2054), ('mixed model', 1998), ('clustering', 1952), ('neural networks', 1897), ('mathematical statistics', 1888), ('confidence interval', 1776), ('categorical data', 1703), ('generalized linear model', 1614), ('variance', 1576), ('data visualization', 1549), ('estimation', 1533), ('forecasting', 1422), ('t test', 1418), ('pca', 1395), ('sampling', 1363), ('cross validation', 1344), ('repeated measures', 1335), ('spss', 1296), ('svm', 1283), ('chi squared', 1261), ('maximum likelihood', 1209), ('predictive models', 1189), ('multivariate analysis', 1116), ('survival', 1081), ('references', 1076), ('data transformation', 1057), ('modeling', 1055), ('p value', 1040), ('feature selection', 997), ('econometrics', 989), ('panel data', 966), ('python', 955), ('data mining', 950), ('interaction', 946), ('matlab', 941), ('linear model', 937), ('binomial', 935), ('random forest', 935), ('nonparametric', 922), ('arima', 917), ('least squares', 898), ('optimization', 898), ('model selection', 876), ('standard deviation', 866), ('poisson', 865), ('interpretation', 860), ('sample size', 847), ('mean', 842), ('stata', 842), ('dataset', 840), ('conditional probability', 837), ('prediction', 832), ('multiple comparisons', 825), ('bootstrap', 814), ('experiment design', 780), ('random variable', 745), ('autocorrelation', 678), ('simulation', 676), ('covariance', 666), ('multilevel analysis', 663), ('pdf', 654), ('missing data', 652), ('expected value', 645), ('regression coefficients', 643), ('factor analysis', 642), ('mcmc', 635), ('outliers', 629), ('standard error', 629), ('inference', 625), ('ordinal', 624), ('survey', 617), ('deep learning', 600), ('cart', 593), ('residuals', 582), ('binary data', 570), ('random effects model', 569), ('goodness of fit', 567), ('model', 567), ('terminology', 551), ('stochastic processes', 530), ('nonlinear regression', 514), ('cox model', 510), ('monte carlo', 504), ('proportion', 503), ('algorithms', 500), ('sas', 496), ('lasso', 490), ('normalization', 484), ('heteroscedasticity', 483), ('error', 481), ('independence', 480), ('meta analysis', 480), ('multinomial', 480), ('k means', 465), ('lmer', 463), ('sample', 450), ('markov process', 445), ('scikit learn', 440), ('multicollinearity', 438), ('text mining', 432), ('aic', 431), ('descriptive statistics', 430), ('spatial', 429), ('assumptions', 418), ('matrix', 413), ('likelihood', 407), ('dimensionality reduction', 407), ('sem', 405), ('bias', 396), ('fixed effects model', 391), ('effect size', 375), ('logit', 374), ('r squared', 372), ('normality', 371), ('lme4', 371), ('convergence', 370), ('likert', 366), ('power analysis', 365), ('glmm', 359), ('negative binomial', 358), ('roc', 358), ('fitting', 357), ('computational statistics', 348), ('count data', 347), ('random generation', 345), ('prior', 340), ('summary statistics', 338), ('ranking', 338), ('stationarity', 337), ('natural language', 335), ('covariance matrix', 332), ('skewness', 325), ('kernel trick', 321), ('gamma distribution', 319), ('naive bayes', 318), ('continuous data', 317), ('regularization', 317), ('hidden markov model', 314), ('reliability', 314), ('power', 312), ('gaussian process', 310), ('group differences', 309), ('autoregressive', 307), ('biostatistics', 306), ('distance', 304), ('garch', 302), ('ancova', 300), ('causality', 300), ('standardization', 300), ('validation', 296), ('small sample', 295), ('exponential', 295), ('quantiles', 293), ('posterior', 291), ('var', 289), ('curve fitting', 288), ('post hoc', 284), ('kernel smoothing', 284), ('robust', 282), ('average', 277), ('gradient descent', 277), ('odds ratio', 275), ('lognormal', 275), ('median', 273), ('bayes', 273), ('seasonality', 270), ('expectation maximization', 270), ('uniform', 268), ('cointegration', 268), ('large data', 266), ('kolmogorov smirnov', 266), ('wilcoxon', 266), ('discrete data', 266), ('conv neural network', 264), ('gaussian mixture', 261), ('histogram', 260), ('non independent', 259), ('entropy', 259), ('pearson', 258), ('excel', 257), ('trend', 256), ('linear', 256), ('arma', 255), ('contingency tables', 253), ('joint distribution', 253), ('pattern recognition', 253), ('manova', 252), ('cdf', 250), ('scales', 248), ('unbalanced classes', 247), ('conditional expectation', 245), ('unbiased estimator', 245), ('mixture', 244), ('measurement error', 243), ('mann whitney u test', 242), ('boosting', 240), ('likelihood ratio', 238), ('data imputation', 238), ('hierarchical bayesian', 237), ('k nearest neighbour', 236), ('central limit theorem', 236), ('asymptotics', 236), ('discriminant analysis', 234), ('caret', 233), ('poisson regression', 233), ('unsupervised learning', 232), ('paired comparisons', 232), ('accuracy', 231), ('permutation', 231), ('graphical model', 231), ('psychometrics', 228), ('ridge regression', 228), ('instrumental variables', 227), ('image processing', 227), ('probit', 226), ('basic concepts', 226), ('similarities', 225), ('multiple imputation', 223), ('distance functions', 222), ('population', 219), ('overfitting', 217), ('predictor', 215), ('gibbs', 215), ('information theory', 212), ('recommender system', 206), ('feature construction', 206), ('estimators', 205), ('degrees of freedom', 205), ('glmnet', 202), ('jags', 201), ('finance', 200), ('gam', 199), ('epidemiology', 198), ('beta distribution', 198), ('proof', 198), ('moments', 198), ('notation', 196), ('linear algebra', 193), ('model comparison', 193), ('bayesian network', 192), ('nonlinear', 191), ('smoothing', 191), ('supervised learning', 191), ('approximation', 187), ('prediction interval', 185), ('cross correlation', 185), ('lme', 183), ('nested', 183), ('svd', 182), ('kalman filter', 180), ('fishers exact', 180), ('bernoulli distribution', 179), ('precision recall', 178), ('libsvm', 177), ('gee', 177), ('measurement', 177), ('latent variable', 177), ('loss functions', 176), ('contrasts', 176), ('zero inflation', 174), ('frequency', 174), ('splines', 173), ('logarithm', 172), ('t distribution', 172), ('auc', 172), ('censoring', 172), ('unit root', 172), ('resampling', 171), ('kruskal wallis', 170), ('intuition', 168), ('uncertainty', 165), ('order statistics', 165), ('hazard', 162), ('regression strategies', 162), ('mediation', 162), ('f test', 162), ('weka', 162), ('graph theory', 160), ('ensemble', 159), ('confirmatory factor', 157), ('definition', 156), ('glmer', 156), ('parametric', 155), ('copula', 155), ('combinatorics', 155), ('polynomial', 154), ('lm', 153), ('performance', 153), ('marginal', 153), ('software', 151), ('signal processing', 151), ('mutual information', 150), ('weighted regression', 150), ('propensity scores', 148), ('bonferroni', 148), ('multi class', 148), ('matching', 147), ('reinforcement learning', 145), ('diagnostic', 145), ('frequentist', 144), ('non stationary', 144), ('methodology', 142), ('genetics', 141), ('pymc', 141), ('dirichlet distribution', 140), ('bic', 139), ('stepwise regression', 139), ('metropolis hastings', 138), ('gbm', 138), ('analysis', 138), ('theory', 137), ('kullback leibler', 137), ('eigenvalues', 136), ('intraclass correlation', 135), ('inter rater', 134), ('paired data', 134), ('difference in difference', 133), ('metric', 132), ('hierarchical', 132), ('error propagation', 131), ('scatterplot', 131), ('multivariate regression', 131), ('interpolation', 130), ('quantile regression', 130), ('multidimensional scaling', 130), ('aggregation', 128), ('mse', 128), ('reporting', 128), ('hierarchical clustering', 128), ('weibull', 128), ('qq plot', 127), ('multivariate normal', 127), ('parameterization', 126), ('train', 126), ('change point', 125), ('irt', 124), ('matrix decomposition', 123), ('sparse', 123), ('topic models', 123), ('bioinformatics', 123), ('bivariate', 122), ('decision theory', 121), ('exponential smoothing', 121), ('lags', 120), ('backpropagation', 120), ('kurtosis', 120), ('poisson process', 119), ('state space models', 119), ('percentage', 119), ('randomization', 119), ('endogeneity', 118), ('ratio', 117), ('weighted mean', 116), ('z test', 116), ('eda', 116), ('spearman', 116), ('exponential family', 115), ('confidence', 115), ('nlme', 114), ('statistical learning', 114), ('probability inequalities', 114), ('false discovery rate', 113), ('networks', 112), ('convolution', 112), ('markov chain', 111), ('extreme value', 111), ('clinical trials', 110), ('autoencoders', 110), ('generalized least squares', 110), ('pls', 109), ('ecology', 109), ('boxplot', 109), ('hyperparameter', 109), ('sums of squares', 109), ('stratification', 109), ('learning', 108), ('teaching', 107), ('ab test', 107), ('conjugate prior', 106), ('sufficient statistics', 106), ('confounding', 106), ('consistency', 106), ('treatment effect', 105), ('ggplot2', 105), ('covariate', 104), ('bugs', 102), ('computer vision', 102), ('online', 100), ('coefficient', 99), ('randomness', 99), ('games', 98), ('granger causality', 98), ('weighted sampling', 98), ('kaplan meier', 97), ('high dimensional', 97), ('elastic net', 97), ('threshold', 96), ('sample mean', 94), ('lstm', 94), ('augmented dickey fuller', 94), ('fisher information', 94), ('rms', 93), ('pooling', 92), ('time varying covariate', 92), ('rpart', 92), ('spearman rho', 92), ('vecm', 92), ('hypergeometric', 92), ('moving average', 92), ('bounds', 92), ('maximum', 91), ('scores', 91), ('fourier transform', 90), ('integral', 90), ('overdispersion', 90), ('scipy', 90), ('type i errors', 90), ('power law', 89), ('residual analysis', 89), ('mathematics', 88), ('deviance', 88), ('binning', 88), ('interval', 87), ('psychology', 87), ('tukey hsd', 87), ('calibration', 87), ('rank correlation', 87), ('nominal', 86), ('intercept', 86), ('model evaluation', 86), ('information retrieval', 85), ('cross section', 85), ('partial correlation', 84), ('dice', 84), ('lme4 nlme', 84), ('z score', 84), ('genetic algorithms', 82), ('truncation', 81), ('partitioning', 81), ('weighted data', 81), ('quality control', 81), ('kappa', 81), ('importance', 80), ('log linear', 79), ('empirical', 79), ('function', 79), ('parameter optimization', 78), ('data preprocessing', 78), ('generalized moments', 77), ('association rules', 77), ('rnn', 77), ('social network', 77), ('sensitivity', 76), ('point estimation', 76), ('bagging', 76), ('matrix inverse', 76), ('java', 75), ('cohens d', 75), ('spectral analysis', 75), ('risk', 75), ('odds', 75), ('out of sample', 74), ('history', 74), ('association measure', 74), ('quadratic form', 74), ('random walk', 74), ('sequence analysis', 74), ('rbm', 74), ('filter', 74), ('centering', 73), ('control', 73), ('clustered standard errors', 73), ('link function', 73), ('maximum entropy', 73), ('deep belief networks', 72), ('artificial intelligence', 72), ('dirichlet process', 72), ('rare events', 72), ('validity', 71), ('mode', 71), ('confusion matrix', 71), ('meta regression', 71), ('pareto distribution', 70), ('winbugs', 70), ('observational study', 70), ('point process', 70), ('method comparison', 69), ('cluster sample', 68), ('circular statistics', 68), ('case control study', 68), ('segmentation', 68), ('shrinkage', 68), ('sequential analysis', 67), ('mcnemar test', 67), ('scoring', 67), ('kendall tau', 67), ('intervention analysis', 67), ('2sls', 66), ('fisher', 65), ('tobit regression', 65), ('loess', 65), ('volatility forecasting', 64), ('mgcv', 64), ('ranks', 64), ('beta binomial', 63), ('dynamic regression', 63), ('inferential statistics', 63), ('stan', 63), ('mice', 62), ('delta method', 62), ('rating', 62), ('iid', 61), ('moderation', 61), ('correspondence analysis', 61), ('anomaly detection', 61), ('method of moments', 61), ('equivalence', 61), ('relative risk', 61), ('hausman', 60), ('euclidean', 60), ('marketing', 60), ('noise', 60), ('minimum', 60), ('efficiency', 60), ('ordered logit', 60), ('numerical integration', 60), ('beta regression', 59), ('identifiability', 59), ('structural change', 59), ('geostatistics', 58), ('vif', 58), ('signal detection', 58), ('derivative', 58), ('traminer', 57), ('variational bayes', 57), ('tensorflow', 57), ('growth model', 57), ('coefficient of variation', 57), ('subset', 56), ('canonical correlation', 56), ('offset', 56), ('latent class', 56), ('spatio temporal', 55), ('multilabel', 55), ('adjustment', 55), ('cronbachs alpha', 55), ('white noise', 54), ('queueing', 54), ('credible interval', 54), ('composite', 53), ('philosophical', 53), ('statsmodels', 52), ('perceptron', 52), ('variogram', 52), ('statistical', 51), ('importance sampling', 51), ('variability', 51), ('mgf', 51), ('nls', 50), ('penalized', 50), ('numerics', 50), ('self organizing maps', 50), ('weights', 50), ('word2vec', 50), ('lsa', 49), ('finite population', 49), ('particle filter', 49), ('amos', 49), ('nonparametric bayes', 49), ('sensitivity analysis', 48), ('specificity', 48), ('education', 48), ('wishart', 48), ('levenes test', 48), ('gradient', 48), ('geometric distribution', 47), ('eviews', 47), ('lsmeans', 47), ('fuzzy', 47), ('density estimation', 46), ('minitab', 46), ('type ii errors', 46), ('robust standard error', 46), ('agreement statistics', 46), ('path model', 46), ('multivariable', 45), ('combining p values', 45), ('model based clustering', 45), ('programming', 45), ('arithmetic', 45), ('word embeddings', 44), ('geometry', 44), ('replication', 44), ('split plot', 44), ('gini', 44), ('microarray', 44), ('blocking', 44), ('rejection sampling', 43), ('macroeconomics', 43), ('constrained regression', 43), ('log likelihood', 43), ('multiarmed bandit', 42), ('code', 42), ('change scores', 42), ('imbalanced', 42), ('brownian', 42), ('clogit', 42), ('conjoint analysis', 42), ('univariate', 42), ('mixed design', 42), ('arch', 41), ('lavaan', 41), ('application', 41), ('jmp', 41), ('conditioning', 41), ('communication', 40), ('z statistic', 40), ('barplot', 40), ('semi supervised', 40), ('measure theory', 40), ('summations', 40), ('data cleaning', 40), ('tables', 39), ('impulse response', 39), ('demography', 39), ('generative models', 39), ('f distribution', 39), ('functional data analysis', 38), ('dlm', 38), ('sentiment analysis', 38), ('curves', 38), ('reproducible research', 38), ('c++', 38), ('back transformation', 38), ('logrank', 37), ('fat tails', 37), ('survey weights', 37), ('umvue', 37), ('mlogit', 37), ('package', 37), ('friedman test', 37), ('plm', 37), ('wavelet', 37), ('fractional factorial', 37), ('uninformative prior', 35), ('cauchy', 35), ('law of large numbers', 35), ('kriging', 35), ('marginal effect', 35), ('signed rank test', 34), ('lars', 34), ('bias correction', 34), ('mathematica', 34), ('formula', 34), ('ica', 34), ('valuation', 33), ('discontinuity', 33), ('projection', 33), ('multiple seasonalities', 33), ('hauck donner effect', 33), ('cosine similarity', 33), ('rotation', 33), ('census', 32), ('heterogeneity', 32), ('dendrogram', 32), ('biplot', 32), ('cholesky', 32), ('radial basis', 32), ('interval censoring', 32), ('error message', 31), ('careers', 31), ('crossover study', 31), ('numpy', 31), ('softmax', 31), ('rule of thumb', 31), ('real time', 31), ('f statistic', 31), ('mplus', 31), ('two way', 31), ('factor rotation', 31), ('anderson darling', 31), ('ecdf', 31), ('web', 31), ('parallel computing', 30), ('piecewise linear', 30), ('igraph', 30), ('oversampling', 30), ('range', 30), ('adaboost', 30), ('dataframe', 30), ('test for trend', 30), ('random matrix', 30), ('dispersion', 30), ('inverse gamma', 29), ('laplace distribution', 29), ('jaccard similarity', 29), ('e1071', 29), ('effects', 29), ('computing', 29), ('business intelligence', 29), ('incidence rate ratio', 29), ('bayes factors', 29), ('heavy tailed', 29), ('errors in variables', 29), ('heckman', 28), ('neyman pearson lemma', 28), ('transition matrix', 28), ('quasi likelihood', 28), ('discriminant', 28), ('model averaging', 28), ('frailty', 28), ('sphericity', 28), ('chemometrics', 28), ('statistical control', 28), ('constraint', 28), ('scale invariance', 28), ('stacking', 27), ('optimal scaling', 27), ('vc dimension', 27), ('social science', 27), ('k medoids', 27), ('moving window', 27), ('indicator variables', 27), ('tolerance interval', 26), ('poisson binomial', 26), ('conditional random field', 26), ('non response', 26), ('correlated predictors', 26), ('nnet', 26), ('apriori', 26), ('spark mllib', 26), ('tbats', 26), ('chow test', 26), ('segmented regression', 26), ('coding', 25), ('total least squares', 25), ('profile likelihood', 25), ('theano', 25), ('interaction variable', 25), ('control chart', 25), ('truncated normal', 25), ('mad', 25), ('cosine distance', 25), ('information', 24), ('big data', 24), ('partial', 24), ('concordance', 24), ('jackknife', 24), ('dropout', 24), ('rapidminer', 24), ('units', 24), ('churn', 24), ('qualitative', 24), ('survey sampling', 24), ('precision', 24), ('trimmed mean', 24), ('time complexity', 23), ('correlation matrix', 23), ('probabilistic programming', 23), ('ecm', 23), ('repeatability', 23), ('leverage', 23), ('subsampling', 23), ('funnel plot', 23), ('convex', 23), ('dunn test', 23), ('jeffreys prior', 23), ('kde', 23), ('sql', 23), ('gumbel', 23), ('characteristic function', 23), ('age', 23), ('representative', 23), ('bimodal', 22), ('skew normal', 22), ('compositional data', 22), ('presentation', 22), ('neuroscience', 22), ('pandas', 22), ('interactive visualization', 22), ('neweywest', 22), ('integration', 22), ('causalimpact', 21), ('finite mixture model', 21), ('non central', 21), ('synthetic data', 21), ('paradox', 21), ('ergodic', 21), ('zero inflated', 21), ('capture mark recapture', 21), ('events', 21), ('sequential pattern mining', 21), ('two step estimation', 21), ('choice', 21), ('geometric mean', 21), ('neuroimaging', 21), ('martingale', 20), ('symmetry', 20), ('c#', 20), ('deming regression', 20), ('optimal stopping', 20), ('publication bias', 20), ('familywise error', 20), ('simpsons paradox', 20), ('interarrival time', 20), ('multivariate distribution', 20), ('taylor series', 20), ('hotelling', 20), ('failure', 20), ('average precision', 20), ('cost maximization', 20), ('determinant', 20), ('project management', 20), ('mancova', 20), ('polling', 19), ('nonparametric regression', 19), ('language models', 19), ('matplotlib', 19), ('compression', 19), ('coverage probability', 19), ('abc', 19), ('competing risks', 19), ('singular', 19), ('bernoulli process', 19), ('fraud', 19), ('box jenkins', 19), ('nnmf', 19), ('decomposition', 19), ('xgboost', 19), ('standard', 19), ('cross entropy', 19), ('elasticity', 19), ('database', 18), ('operations research', 18), ('variance decomposition', 18), ('phylogeny', 18), ('scoring rules', 18), ('hessian', 18), ('differences', 18), ('tsne', 18), ('zipf', 18), ('pivot', 17), ('non nested', 17), ('data association', 17), ('cfa', 17), ('directional statistics', 17), ('overlapping data', 17), ('steins phenomenon', 17), ('recurrent events', 17), ('sign test', 17), ('heatmap', 17), ('planned comparisons test', 17), ('fisher transform', 17), ('academia', 17), ('dbscan', 17), ('tost', 17), ('proportional hazards', 16), ('underdispersion', 16), ('open bugs', 16), ('manifold learning', 16), ('fuzzy set', 16), ('one class', 16), ('linearity', 16), ('coupon collector problem', 16), ('sandwich', 16), ('mape', 16), ('cramers v', 16), ('reml', 16), ('index decomposition', 15), ('gis', 15), ('inequality', 15), ('rbf network', 15), ('heuristic', 15), ('gamm4', 15), ('lrt', 15), ('matrix calculus', 15), ('dependence', 15), ('climate', 15), ('extrapolation', 15), ('rasch', 15), ('dag', 15), ('fractal', 15), ('exact test', 15), ('mortality', 15)

In [75]:
# Top 10 most frequent tags
common_tags = list(freq.keys())[:10]
common_tags

['r',
 'regression',
 'machine learning',
 'time series',
 'probability',
 'hypothesis testing',
 'self study',
 'distributions',
 'logistic',
 'classification']

We will use only those questions/queries that have the above 10 tags associated with it.

In [76]:
x=[]
y=[]

for i in range(len(df['tags'])):

  temp=[]
  for j in df['tags'][i]:
    if j in common_tags:
      temp.append(j)

  if(len(temp)>1):
    x.append(df['cleaned_text'][i])
    y.append(temp)

In [77]:
# number of questions left
len(x)

11106

In [78]:
y[:10]

[['r', 'time series'],
 ['regression', 'distributions'],
 ['distributions', 'probability', 'hypothesis testing'],
 ['hypothesis testing', 'self study'],
 ['r', 'regression', 'time series'],
 ['r', 'time series', 'self study'],
 ['probability', 'hypothesis testing'],
 ['r', 'regression'],
 ['r', 'regression'],
 ['regression', 'logistic']]

In [79]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()

y = mlb.fit_transform(y)
y.shape

(11106, 10)

In [80]:
y[0,:]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [81]:
mlb.classes_

array(['classification', 'distributions', 'hypothesis testing',
       'logistic', 'machine learning', 'probability', 'r', 'regression',
       'self study', 'time series'], dtype=object)

We can now split the dataset into training set and validation set.

In [82]:
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val=train_test_split(x, y, test_size=0.2, random_state=0,shuffle=True)

# Text Representation

In [83]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

#prepare a tokenizer
x_tokenizer = Tokenizer()

x_tokenizer.fit_on_texts(x_tr)

In [84]:
x_tokenizer.word_index

{'the': 1,
 'i': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'is': 6,
 'and': 7,
 'in': 8,
 'l': 9,
 'x': 10,
 'for': 11,
 'that': 12,
 'data': 13,
 'this': 14,
 't': 15,
 'have': 16,
 'y': 17,
 'with': 18,
 'model': 19,
 'it': 20,
 'are': 21,
 'be': 22,
 'my': 23,
 'as': 24,
 'on': 25,
 'e': 26,
 'p': 27,
 'if': 28,
 'can': 29,
 'n': 30,
 'but': 31,
 'not': 32,
 'm': 33,
 'or': 34,
 'r': 35,
 'how': 36,
 'regression': 37,
 'c': 38,
 'am': 39,
 's': 40,
 'from': 41,
 'test': 42,
 'what': 43,
 'would': 44,
 'b': 45,
 'so': 46,
 'time': 47,
 'there': 48,
 'using': 49,
 'which': 50,
 'an': 51,
 'do': 52,
 'one': 53,
 'each': 54,
 'value': 55,
 'use': 56,
 'by': 57,
 'some': 58,
 'variables': 59,
 'like': 60,
 'variable': 61,
 'we': 62,
 'at': 63,
 'na': 64,
 'any': 65,
 'f': 66,
 'distribution': 67,
 'two': 68,
 'values': 69,
 'set': 70,
 'you': 71,
 'all': 72,
 'function': 73,
 'fit': 74,
 'd': 75,
 'beta': 76,
 'question': 77,
 'then': 78,
 'mean': 79,
 'me': 80,
 'know': 81,
 'where': 82,
 'when': 83,
 'should': 84,
 'different': 85,
 'want': 86,
 'series': 87,
 'probability': 88,
 'error': 89,
 'number': 90,
 'logistic': 91,
 'problem': 92,
 'about': 93,
 'z': 94,
 'here': 95,
 'k': 96,
 'get': 97,
 'was': 98,
 'linear': 99,
 'other': 100,
 'more': 101,
 'will': 102,
 'sample': 103,
 'between': 104,
 'also': 105,
 'these': 106,
 'has': 107,
 'example': 108,
 'frac': 109,
 'way': 110,
 'same': 111,
 'sum': 112,
 'out': 113,
 'right': 114,
 'only': 115,
 'h': 116,
 'following': 117,
 'could': 118,
 'does': 119,
 'random': 120,
 'than': 121,
 'log': 122,
 'first': 123,
 'given': 124,
 'find': 125,
 'used': 126,
 'however': 127,
 'models': 128,
 'they': 129,
 'no': 130,
 'theta': 131,
 'class': 132,
 'just': 133,
 'predict': 134,
 'df': 135,
 'results': 136,
 'q': 137,
 'w': 138,
 'trying': 139,
 'now': 140,
 'training': 141,
 'coefficients': 142,
 'need': 143,
 'plot': 144,
 'v': 145,
 'g': 146,
 'method': 147,
 'j': 148,
 'case': 149,
 'dataset': 150,
 'very': 151,
 'help': 152,
 'true': 153,
 'lm': 154,
 'estimate': 155,
 'sigma': 156,
 'into': 157,
 'see': 158,
 'alpha': 159,
 'don': 160,
 've': 161,
 'say': 162,
 'matrix': 163,
 'package': 164,
 'such': 165,
 'classification': 166,
 'code': 167,
 'factor': 168,
 'analysis': 169,
 'because': 170,
 'understand': 171,
 'left': 172,
 'why': 173,
 'hat': 174,
 'thanks': 175,
 'independent': 176,
 'intercept': 177,
 'new': 178,
 'based': 179,
 'type': 180,
 'group': 181,
 'glm': 182,
 'correct': 183,
 'best': 184,
 'order': 185,
 'make': 186,
 'let': 187,
 'standard': 188,
 'u': 189,
 'both': 190,
 'output': 191,
 'mu': 192,
 'good': 193,
 'possible': 194,
 'over': 195,
 'arima': 196,
 'them': 197,
 'text': 198,
 'approach': 199,
 'binomial': 200,
 'age': 201,
 'features': 202,
 'response': 203,
 'year': 204,
 'point': 205,
 'something': 206,
 'significant': 207,
 'whether': 208,
 'better': 209,
 'points': 210,
 'up': 211,
 'think': 212,
 'been': 213,
 'parameters': 214,
 'residuals': 215,
 'observations': 216,
 'formula': 217,
 'sure': 218,
 'calculate': 219,
 'train': 220,
 'since': 221,
 'binary': 222,
 'run': 223,
 'size': 224,
 'summary': 225,
 'variance': 226,
 'non': 227,
 'hypothesis': 228,
 'var': 229,
 'above': 230,
 'below': 231,
 'end': 232,
 'after': 233,
 'length': 234,
 'learning': 235,
 'normal': 236,
 'lambda': 237,
 'level': 238,
 'result': 239,
 'dependent': 240,
 'difference': 241,
 'family': 242,
 'seems': 243,
 'tried': 244,
 'forecast': 245,
 'null': 246,
 'times': 247,
 'many': 248,
 'prediction': 249,
 'doing': 250,
 'questions': 251,
 'much': 252,
 'max': 253,
 'effect': 254,
 'answer': 255,
 'looking': 256,
 'well': 257,
 'pr': 258,
 'classifier': 259,
 'parameter': 260,
 'vector': 261,
 'continuous': 262,
 'multiple': 263,
 'were': 264,
 'found': 265,
 'please': 266,
 'may': 267,
 'squared': 268,
 'library': 269,
 'their': 270,
 'samples': 271,
 'most': 272,
 'simple': 273,
 'predictor': 274,
 'frame': 275,
 'likelihood': 276,
 'etc': 277,
 'second': 278,
 'correlation': 279,
 'predictors': 280,
 'being': 281,
 'give': 282,
 'change': 283,
 'list': 284,
 'score': 285,
 'accuracy': 286,
 'feature': 287,
 'outcome': 288,
 'might': 289,
 'really': 290,
 'its': 291,
 'day': 292,
 'information': 293,
 'even': 294,
 'similar': 295,
 'means': 296,
 'epsilon': 297,
 'categorical': 298,
 'equation': 299,
 'take': 300,
 'false': 301,
 'min': 302,
 'work': 303,
 'those': 304,
 'input': 305,
 'anyone': 306,
 'std': 307,
 'look': 308,
 'another': 309,
 'exp': 310,
 'suppose': 311,
 'zero': 312,
 'average': 313,
 'read': 314,
 'total': 315,
 'mathbf': 316,
 'before': 317,
 'logit': 318,
 'terms': 319,
 'effects': 320,
 'three': 321,
 'algorithm': 322,
 'compare': 323,
 'ts': 324,
 'interval': 325,
 'gamma': 326,
 'still': 327,
 'show': 328,
 'negative': 329,
 'working': 330,
 'probabilities': 331,
 'high': 332,
 'machine': 333,
 'table': 334,
 'having': 335,
 'cross': 336,
 'confidence': 337,
 'start': 338,
 'testing': 339,
 'predicted': 340,
 'statistical': 341,
 'while': 342,
 'did': 343,
 'your': 344,
 'rate': 345,
 'levels': 346,
 'wrong': 347,
 'groups': 348,
 'large': 349,
 'assume': 350,
 'scale': 351,
 'coefficient': 352,
 'bar': 353,
 'line': 354,
 'residual': 355,
 'statistics': 356,
 'days': 357,
 'positive': 358,
 'call': 359,
 'methods': 360,
 'distributions': 361,
 'phi': 362,
 'someone': 363,
 'term': 364,
 'edit': 365,
 'cases': 366,
 'every': 367,
 'far': 368,
 'able': 369,
 'process': 370,
 'statistic': 371,
 'people': 372,
 'determine': 373,
 'fitted': 374,
 'gives': 375,
 'step': 376,
 'validation': 377,
 'lag': 378,
 'deviance': 379,
 'appreciated': 380,
 'part': 381,
 'sqrt': 382,
 'ratio': 383,
 'thank': 384,
 'form': 385,
 'tests': 386,
 'classes': 387,
 'without': 388,
 'degrees': 389,
 'freedom': 390,
 'idea': 391,
 'try': 392,
 'rep': 393,
 'aic': 394,
 'within': 395,
 'least': 396,
 'measure': 397,
 'around': 398,
 'got': 399,
 'perform': 400,
 'sim': 401,
 'done': 402,
 'per': 403,
 'doesn': 404,
 'had': 405,
 'create': 406,
 'sense': 407,
 'link': 408,
 'real': 409,
 'rnorm': 410,
 'interaction': 411,
 'price': 412,
 'median': 413,
 'explain': 414,
 'trend': 415,
 'month': 416,
 'vs': 417,
 'follows': 418,
 'specific': 419,
 'chi': 420,
 'years': 421,
 'weight': 422,
 'yes': 423,
 'begin': 424,
 'population': 425,
 'looks': 426,
 'particular': 427,
 'id': 428,
 'kind': 429,
 'state': 430,
 'missing': 431,
 'event': 432,
 'control': 433,
 'less': 434,
 'go': 435,
 'expected': 436,
 'equal': 437,
 'small': 438,
 'sd': 439,
 'wondering': 440,
 'compute': 441,
 'performance': 442,
 'errors': 443,
 'too': 444,
 'actually': 445,
 'single': 446,
 'distributed': 447,
 'several': 448,
 'apply': 449,
 'svm': 450,
 'seem': 451,
 'treatment': 452,
 'observation': 453,
 'estimates': 454,
 'weights': 455,
 'either': 456,
 'consider': 457,
 'frequency': 458,
 'density': 459,
 'instead': 460,
 'cannot': 461,
 'thought': 462,
 'check': 463,
 'int': 464,
 'sets': 465,
 'estimated': 466,
 'solution': 467,
 'interested': 468,
 'certain': 469,
 'range': 470,
 'general': 471,
 'power': 472,
 'date': 473,
 'sales': 474,
 'low': 475,
 'quite': 476,
 'appropriate': 477,
 'choose': 478,
 'solve': 479,
 'poisson': 480,
 'our': 481,
 'through': 482,
 'col': 483,
 'few': 484,
 'odds': 485,
 'anova': 486,
 'pi': 487,
 'next': 488,
 'dummy': 489,
 'numeric': 490,
 'period': 491,
 'http': 492,
 'individual': 493,
 'fixed': 494,
 'last': 495,
 'figure': 496,
 'factors': 497,
 'add': 498,
 'original': 499,
 'build': 500,
 'subject': 501,
 'pred': 502,
 'significance': 503,
 'mod': 504,
 'getting': 505,
 'higher': 506,
 'fitting': 507,
 'include': 508,
 'note': 509,
 'across': 510,
 'delta': 511,
 'running': 512,
 'calculated': 513,
 'examples': 514,
 'predictions': 515,
 'ar': 516,
 'paper': 517,
 'lower': 518,
 'advance': 519,
 'actual': 520,
 'relationship': 521,
 'return': 522,
 'count': 523,
 'structure': 524,
 'lot': 525,
 'who': 526,
 'infty': 527,
 'functions': 528,
 'red': 529,
 'related': 530,
 'product': 531,
 'observed': 532,
 'selection': 533,
 'interpret': 534,
 'codes': 535,
 'dat': 536,
 'generate': 537,
 'under': 538,
 'though': 539,
 'currently': 540,
 'category': 541,
 'square': 542,
 'label': 543,
 'rather': 544,
 'understanding': 545,
 'numbers': 546,
 'cost': 547,
 'course': 548,
 'target': 549,
 'made': 550,
 'distance': 551,
 'exactly': 552,
 'space': 553,
 'previous': 554,
 'coef': 555,
 'constant': 556,
 'main': 557,
 'thinking': 558,
 'curve': 559,
 'problems': 560,
 'scores': 561,
 'bit': 562,
 'gaussian': 563,
 'thus': 564,
 'mathbb': 565,
 'simply': 566,
 'prior': 567,
 'always': 568,
 'therefore': 569,
 'final': 570,
 'alternative': 571,
 'going': 572,
 'likely': 573,
 'network': 574,
 'maybe': 575,
 'tree': 576,
 'book': 577,
 'lines': 578,
 'sex': 579,
 'leq': 580,
 'object': 581,
 'seasonal': 582,
 'study': 583,
 'row': 584,
 'long': 585,
 'big': 586,
 'auto': 587,
 'known': 588,
 'fact': 589,
 'slope': 590,
 'column': 591,
 'account': 592,
 'come': 593,
 'user': 594,
 'signif': 595,
 'important': 596,
 'differences': 597,
 'rows': 598,
 'events': 599,
 'due': 600,
 'words': 601,
 'neural': 602,
 'daily': 603,
 'se': 604,
 'names': 605,
 'post': 606,
 'full': 607,
 'procedure': 608,
 'tell': 609,
 'already': 610,
 'mydata': 611,
 'adjusted': 612,
 'gender': 613,
 'forest': 614,
 'makes': 615,
 're': 616,
 'seed': 617,
 'decision': 618,
 'appreciate': 619,
 'he': 620,
 'pdf': 621,
 'maximum': 622,
 'index': 623,
 'print': 624,
 'current': 625,
 'algorithms': 626,
 'deviation': 627,
 'shape': 628,
 'reading': 629,
 'issue': 630,
 'system': 631,
 'seasonality': 632,
 'provide': 633,
 'reason': 634,
 'increase': 635,
 'enough': 636,
 'ols': 637,
 'again': 638,
 'intervals': 639,
 'shows': 640,
 'confused': 641,
 'amount': 642,
 'csv': 643,
 'conditional': 644,
 'cdot': 645,
 'proportion': 646,
 'com': 647,
 'labels': 648,
 'guess': 649,
 'taken': 650,
 'significantly': 651,
 'graph': 652,
 'taking': 653,
 'diff': 654,
 'rank': 655,
 'learn': 656,
 'according': 657,
 'stationary': 658,
 'acf': 659,
 'page': 660,
 'noise': 661,
 'categories': 662,
 'obtain': 663,
 'update': 664,
 'datasets': 665,
 'success': 666,
 'correctly': 667,
 'person': 668,
 'down': 669,
 'against': 670,
 'bad': 671,
 'classify': 672,
 'must': 673,
 'threshold': 674,
 'sampling': 675,
 'instance': 676,
 'assumption': 677,
 'close': 678,
 'suggestions': 679,
 'columns': 680,
 'student': 681,
 'defined': 682,
 'cbind': 683,
 'partial': 684,
 'condition': 685,
 'name': 686,
 'temperature': 687,
 'greater': 688,
 'else': 689,
 'things': 690,
 'anything': 691,
 'loss': 692,
 'seen': 693,
 'believe': 694,
 'little': 695,
 'blue': 696,
 'assuming': 697,
 'male': 698,
 'correlated': 699,
 'statistically': 700,
 'suggest': 701,
 'direction': 702,
 'support': 703,
 'experiment': 704,
 'goal': 705,
 'area': 706,
 'predictive': 707,
 'week': 708,
 'vectors': 709,
 'basic': 710,
 'cv': 711,
 'classifiers': 712,
 'available': 713,
 'iv': 714,
 'region': 715,
 'subset': 716,
 'ldots': 717,
 'explanatory': 718,
 'discrete': 719,
 'off': 720,
 'chance': 721,
 'select': 722,
 'reference': 723,
 'split': 724,
 'works': 725,
 'us': 726,
 'ones': 727,
 'ways': 728,
 'shown': 729,
 'task': 730,
 'transformation': 731,
 'clear': 732,
 'seq': 733,
 'multivariate': 734,
 'obtained': 735,
 'trees': 736,
 'rm': 737,
 'unit': 738,
 'thing': 739,
 'during': 740,
 'estimation': 741,
 'ab': 742,
 'contains': 743,
 'basically': 744,
 'st': 745,
 'align': 746,
 'months': 747,
 'normally': 748,
 'follow': 749,
 'future': 750,
 'array': 751,
 'female': 752,
 'advice': 753,
 'mathcal': 754,
 'measures': 755,
 'roc': 756,
 'vec': 757,
 'income': 758,
 'others': 759,
 'isn': 760,
 'forecasting': 761,
 'default': 762,
 'packages': 763,
 'further': 764,
 'pattern': 765,
 'returns': 766,
 'changes': 767,
 'covariates': 768,
 'write': 769,
 'asked': 770,
 'squares': 771,
 'randomly': 772,
 'bayes': 773,
 'prob': 774,
 'temp': 775,
 'finding': 776,
 'overall': 777,
 'corresponding': 778,
 'initial': 779,
 'multinomial': 780,
 'bayesian': 781,
 'res': 782,
 'exponential': 783,
 'useful': 784,
 'iterations': 785,
 'ran': 786,
 'measured': 787,
 'four': 788,
 'stats': 789,
 'predicting': 790,
 'exact': 791,
 'generated': 792,
 'situation': 793,
 'sort': 794,
 'monthly': 795,
 'pretty': 796,
 'probably': 797,
 'll': 798,
 'students': 799,
 'research': 800,
 'including': 801,
 'naive': 802,
 'rho': 803,
 'represent': 804,
 'glmnet': 805,
 'plots': 806,
 'sequence': 807,
 'image': 808,
 'measurements': 809,
 'once': 810,
 'put': 811,
 'ln': 812,
 'cluster': 813,
 'uses': 814,
 'ml': 815,
 'th': 816,
 'implement': 817,
 'past': 818,
 'mixed': 819,
 'types': 820,
 'ordinal': 821,
 'compared': 822,
 'hidden': 823,
 'season': 824,
 'combination': 825,
 'covariance': 826,
 'ask': 827,
 'although': 828,
 'uniform': 829,
 'steps': 830,
 'risk': 831,
 'np': 832,
 'answers': 833,
 'cov': 834,
 'says': 835,
 'applied': 836,
 'project': 837,
 'created': 838,
 'choice': 839,
 'relative': 840,
 'hand': 841,
 'raw': 842,
 'valid': 843,
 'head': 844,
 'species': 845,
 'gradient': 846,
 'called': 847,
 'num': 848,
 'whole': 849,
 'easy': 850,
 'associated': 851,
 'selected': 852,
 'larger': 853,
 'perhaps': 854,
 'match': 855,
 'site': 856,
 'dots': 857,
 'tau': 858,
 'o': 859,
 'obs': 860,
 'among': 861,
 'techniques': 862,
 'expect': 863,
 'nrow': 864,
 'back': 865,
 'top': 866,
 'transform': 867,
 'common': 868,
 'comes': 869,
 'file': 870,
 'omega': 871,
 'dv': 872,
 'adding': 873,
 'regarding': 874,
 'auc': 875,
 'wanted': 876,
 'optimal': 877,
 'scaled': 878,
 'survival': 879,
 'comparing': 880,
 'modeling': 881,
 'regressions': 882,
 'define': 883,
 'quad': 884,
 'knowledge': 885,
 'building': 886,
 'importance': 887,
 'context': 888,
 'fold': 889,
 'approaches': 890,
 'game': 891,
 'weighted': 892,
 'outliers': 893,
 'reject': 894,
 'obviously': 895,
 'hope': 896,
 'various': 897,
 'status': 898,
 'present': 899,
 'additional': 900,
 'customer': 901,
 'estimator': 902,
 'background': 903,
 'takes': 904,
 'added': 905,
 'specifically': 906,
 'www': 907,
 'box': 908,
 'own': 909,
 'individuals': 910,
 'otherwise': 911,
 'component': 912,
 'keep': 913,
 'self': 914,
 'assumptions': 915,
 'interest': 916,
 'ma': 917,
 'components': 918,
 'subjects': 919,
 'require': 920,
 'attributes': 921,
 'highly': 922,
 'suggested': 923,
 'root': 924,
 'greatly': 925,
 'interpretation': 926,
 'axis': 927,
 'states': 928,
 'included': 929,
 'often': 930,
 'implementation': 931,
 'hence': 932,
 'remove': 933,
 'option': 934,
 'patients': 935,
 'separate': 936,
 'fisher': 937,
 'python': 938,
 'theory': 939,
 'considered': 940,
 'explanation': 941,
 'white': 942,
 'identify': 943,
 'trained': 944,
 'window': 945,
 'location': 946,
 'almost': 947,
 'kernel': 948,
 'prices': 949,
 'simulation': 950,
 'unknown': 951,
 'inputs': 952,
 'great': 953,
 'polynomial': 954,
 'qu': 955,
 'deal': 956,
 'percentage': 957,
 'autocorrelation': 958,
 'balls': 959,
 'overline': 960,
 'outputs': 961,
 'bootstrap': 962,
 'improve': 963,
 'wt': 964,
 'none': 965,
 'bias': 966,
 'calculating': 967,
 'reasonable': 968,
 'limits': 969,
 'evaluate': 970,
 'usually': 971,
 'posterior': 972,
 'came': 973,
 'upper': 974,
 'pca': 975,
 'relevant': 976,
 'ideas': 977,
 'fits': 978,
 'users': 979,
 'together': 980,
 'items': 981,
 'ci': 982,
 'outcomes': 983,
 'prove': 984,
 'runif': 985,
 'along': 986,
 'unfortunately': 987,
 'hour': 988,
 'trials': 989,
 'conditions': 990,
 'randomforest': 991,
 'message': 992,
 'making': 993,
 'lasso': 994,
 'sub': 995,
 'stat': 996,
 'feel': 997,
 'command': 998,
 'le': 999,
 'instances': 1000,
 ...}

In [85]:
len(x_tokenizer.word_index)

25315

There are around 25,000 tokens in the training dataset. Let's see how many tokens appear at least 5 times in the dataset.

In [86]:
thresh = 3

cnt=0
for key,value in x_tokenizer.word_counts.items():
  if value>=thresh:
    cnt=cnt+1

print(cnt)

12575

Over 12,000 tokens have appeared three times or more in the training set.

In [87]:
# prepare the tokenizer again
x_tokenizer = Tokenizer(num_words=cnt,oov_token='unk')

#prepare vocabulary
x_tokenizer.fit_on_texts(x_tr)

Now that we have encoded every token to an integer, let's convert the text sequences to integer sequences. After that we will pad the integer sequences to the maximum sequence length, i.e., 100.

In [88]:
# maximum sequence length allowed
max_len = 100

#convert text sequences into integer sequences
x_tr_seq = x_tokenizer.texts_to_sequences(x_tr)
x_val_seq = x_tokenizer.texts_to_sequences(x_val)

#padding up with zero
x_tr_seq = pad_sequences(x_tr_seq,  padding='post', maxlen=max_len)
x_val_seq = pad_sequences(x_val_seq, padding='post', maxlen=max_len)

Since we are padding the sequences with zeros, we must increment the vocabulary size by one.

In [89]:
#no. of unique words
x_voc_size = x_tokenizer.num_words + 1
x_voc_size

12576

In [90]:
x_tr_seq[0]

array([1953, 5711,  416, 2023,    1,  226, 1747, 3740,  609,   43,  181,
       1953,  372,   19,  100,  416,    9, 1747, 3839,  238,   27,   27,
         27,   27,   27,   70,    6, 6919,    8, 1163,   70,    6,   43,
         43, 1802, 1802, 1802,   36,   36,   36,   36, 4308, 5410,    4,
        124,  592,  107,   22,    2, 1747, 4065,   27,   10, 1309,   10,
       6415,   10,  190,   10,  416,   10,   27,   10, 1309,   10, 6415,
         10,  190,   10,  416,   10,  456,  139,   15,    7,    2, 4610,
        164,   27,   10, 1309,   10, 6415,   10,  190,   10,  416,   10,
         27,   76,   27, 1309,   76,   27, 6415,   76,   27,  190,   76,
         27], dtype=int32)

# Model Building

In [91]:
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import *

### Define Model Architecture

In [92]:
#sequential model
model = Sequential()

#embedding layer
model.add(Embedding(x_voc_size, 50, input_shape=(max_len,), mask_zero=True))

#rnn layer
model.add(SimpleRNN(128,activation='relu'))

#dense layer
model.add(Dense(128,activation='relu'))

#output layer
model.add(Dense(10,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Understand the output shape and no. of parameters of each layer:

In [93]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 100, 50)        │       628,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 128)            │        22,912 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 669,514 (2.55 MB)

 Trainable params: 669,514 (2.55 MB)

 Non-trainable params: 0 (0.00 B)

Define the optimizer and loss:

In [94]:
#define optimizer and loss
model.compile(optimizer='adam',loss='binary_crossentropy')

Define a callback - Model Checkpoint. Model Checkpoint is a callback used to save the best model during training.

In [95]:
# checkpoint to save best model during training
mc = ModelCheckpoint("weights.best.keras", monitor='val_loss', verbose=1, save_best_only=True, mode='min')

### Train the Model

Lets train the model for 10 epochs with a batch size of 128:

In [96]:
#train the model
model.fit(x_tr_seq, y_tr, batch_size=128, epochs=10, verbose=1, validation_data=(x_val_seq, y_val), callbacks=[mc])

Epoch 1/10
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.5556
Epoch 1: val_loss improved from None to 0.47762, saving model to weights.best.keras

Epoch 1: finished saving model to weights.best.keras
70/70 ━━━━━━━━━━━━━━━━━━━━ 8s 76ms/step - loss: 0.5061 - val_loss: 0.4776
Epoch 2/10
68/70 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.4701
Epoch 2: val_loss improved from 0.47762 to 0.44609, saving model to weights.best.keras

Epoch 2: finished saving model to weights.best.keras
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.4660 - val_loss: 0.4461
Epoch 3/10
66/70 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4224
Epoch 3: val_loss improved from 0.44609 to 0.42614, saving model to weights.best.keras

Epoch 3: finished saving model to weights.best.keras
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.4148 - val_loss: 0.4261
Epoch 4/10
66/70 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3894
Epoch 4: val_loss improved from 0.42614 to 0.39890, saving model to weights.best.keras

Epoch 4: finished saving model to weights.best.keras
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3861 - val_loss: 0.3989
Epoch 5/10
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3527
Epoch 5: val_loss did not improve from 0.39890
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3548 - val_loss: 0.3994
Epoch 6/10
67/70 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3342
Epoch 6: val_loss improved from 0.39890 to 0.39630, saving model to weights.best.keras

Epoch 6: finished saving model to weights.best.keras
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3296 - val_loss: 0.3963
Epoch 7/10
66/70 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3070
Epoch 7: val_loss did not improve from 0.39630
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3061 - val_loss: 0.4149
Epoch 8/10
68/70 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2981
Epoch 8: val_loss did not improve from 0.39630
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2951 - val_loss: 0.4117
Epoch 9/10
67/70 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2701
Epoch 9: val_loss did not improve from 0.39630
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2657 - val_loss: 0.4092
Epoch 10/10
68/70 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2422
Epoch 10: val_loss did not improve from 0.39630
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2413 - val_loss: 0.4202

# Model Predictions

Load the best model weights and now, the model is ready for the predictions

In [97]:
# load weights into new model
model.load_weights("weights.best.keras")

#predict probabilities
pred_prob = model.predict(x_val_seq)

70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step

In [98]:
pred_prob[0]

array([0.18301648, 0.01857131, 0.05685108, 0.4091714 , 0.3341609 ,
       0.01288784, 0.4939264 , 0.75858176, 0.0401117 , 0.06935683],
      dtype=float32)

The predictions are in terms of probabilities for each of the 10 tags. Hence we need to have a threshold value to convert these probabilities to 0 or 1.

Let's specify a set of candidate threshold values. We will select the threshold value that performs the best for the validation set.

In [100]:
#define candidate threshold values
import numpy as np
threshold  = np.arange(0,0.5,0.01)
threshold

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49])

Let's define a function that takes a threshold value and uses it to convert probabilities into 1 or 0.

In [101]:
# convert probabilities into classes or tags based on a threshold value
def classify(pred_prob,thresh):
  y_pred_seq = []

  for i in pred_prob:
    temp=[]
    for j in i:
      if j>=thresh:
        temp.append(1)
      else:
        temp.append(0)
    y_pred_seq.append(temp)

  return y_pred_seq

In [102]:
from sklearn import metrics
score=[]

#convert to 1 array
y_true = np.array(y_val).ravel()

for thresh in threshold:

    #classes for each threshold
    y_pred_seq = classify(pred_prob,thresh)

    #convert to 1d array
    y_pred = np.array(y_pred_seq).ravel()

    score.append(metrics.f1_score(y_true,y_pred))

In [103]:
# find the optimal threshold
opt = threshold[score.index(max(score))]
opt

np.float64(0.34)

# Model Evaluation

In [104]:
#predictions for optimal threshold
y_pred_seq = classify(pred_prob,opt)
y_pred = np.array(y_pred_seq).ravel()

In [105]:
print(metrics.classification_report(y_true,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.85      0.87     17520
           1       0.52      0.61      0.56      4700

    accuracy                           0.80     22220
   macro avg       0.71      0.73      0.72     22220
weighted avg       0.81      0.80      0.80     22220

In [106]:
y_pred = mlb.inverse_transform(np.array(y_pred_seq))
y_true = mlb.inverse_transform(np.array(y_val))

df = pd.DataFrame({'comment':x_val,'actual':y_true,'predictions':y_pred})

In [107]:
df.sample(10)

,comment,actual,predictions
443,i have a model that i need to estimate where i ve seen a similar example constrained regression in r coefficients positive sum to and non zero intercept but without the second part of the regressi...,"(r, time series)","(logistic, r, regression)"
641,i m investigating optimal bidding in auctions and am using logistic regression to predict the probability of winning an auction given a set of explanatory variables e g the price i bid number of c...,"(logistic, regression)","(logistic, regression)"
698,a binomial glm can be written as y i thicksim b pi i mathrm e y i pi i and mathrm var y i pi i times pi i mathrm logit pi i mathrm intercept beta times treatment i if we consider a simplest model ...,"(logistic, regression)","(logistic, machine learning, r, regression)"
222,i have a time series dataset collected by a group of biologists counting the abundance of a particular animal species in an area i later enriched this dataset with weather variables e g temperatur...,"(machine learning, regression)","(logistic, regression)"
522,the structure of this question is as follows at first i provide the concept of ensemble learning further i provide a list of pattern recognition tasks then i give examples of ensemble learning alg...,"(classification, machine learning)","(classification, machine learning, r)"
924,i have a baseline algorithm and lots of test algorithms the baseline algorithm s performance is compared to every other algorithm what i m left with is a table like so algorithm time worse than ba...,"(classification, machine learning)","(classification, machine learning)"
495,i have fit a probit model in r however in addition to the z and p values i would like to know the wald chi values for the individual explanatory variables how do i obtain calculate the wald chi va...,"(r, regression)","(logistic, r, regression)"
372,i have a question about the effects of shifting the intercept in a logistic fit on the mean of a particular transformation of the scores here is the notation i will be using for the question the l...,"(logistic, machine learning)","(logistic, regression)"
1533,suppose x x n are iid from n mu sigma with mu unknown and sigma known letting t x sum x i mu from i to how can i use the central limit theorem to approximate p t x i found that e t x and var t x a...,"(probability, self study)","(distributions, probability, self study)"
420,i have a problem with logistic regression i want to find out if there is any effect of social capital variables civic participation generalized trust on different dependent variables namely self r...,"(logistic, regression)","(logistic, r, regression)"

### Inference

In [108]:
def predict_tag(comment):
  text=[]

  #preprocess
  text = [cleaner(comment)]

  #convert to integer sequences
  seq = x_tokenizer.texts_to_sequences(text)

  #pad the sequence
  pad_seq = pad_sequences(seq,  padding='post', maxlen=max_len)

  #make predictions
  pred_prob = model.predict(pad_seq)
  classes = classify(pred_prob,opt)[0]

  classes = np.array([classes])
  classes = mlb.inverse_transform(classes)
  return classes

In [109]:
comment = "For example, in the case of logistic regression, the learning function is a Sigmoid function that tries to separate the 2 classes"

print("Comment:",comment)
print("Predicted Tags:",predict_tag(comment))

Comment: For example, in the case of logistic regression, the learning function is a Sigmoid function that tries to separate the 2 classes
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step
Predicted Tags: [('classification', 'machine learning', 'regression')]